#!/usr/bin/python
#-*-coding : utf8-*-
import os
import datetime
from dateutil.relativedelta import relativedelta


def mkdir(path):  #创建指定目录
    # 去除首位空格
    path=path.strip()
    # 去除尾部 \ 符号
    path=path.rstrip("\\")
    # 判断路径是否存在
    isExists=os.path.exists(path)
    if not isExists:
        os.makedirs(path) 
        print(path+' successfully made')
        return True
    else:
        # 如果目录存在则不创建，并提示目录已存在
        print(path+' exists')
        return False

def int2str_2(num): #将正整数转化为两位的字符串。如：2-->"02",11->"11"
    if(int(num) >= 10):
        return str(num)
    else:
        return '0'+str(num)

def get_month_len(year=2017,month=8):    #获得某月日期数。返回字符串。
    begin_date = datetime.datetime(year,month,1)
    end_date = begin_date + relativedelta(months=1)
    d = (end_date-begin_date).days
    return str(d)

def make_trapezoid_area(program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker"):
    with open(program_dir+'/emidata/trapezoid_area.dat', 'w') as f:
        f.write('0 12308.90  \n')
        f.write('1 12305.25  \n')
        f.write('2 12297.95  \n')
        f.write('3 12287.01  \n')
        f.write('4 12272.42  \n')
        f.write('5 12254.19  \n')
        f.write('6 12232.33  \n')
        f.write('7 12206.83  \n')
        f.write('8 12177.71  \n')
        f.write('9 12144.97  \n')
        f.write('10 12108.61  \n')
        f.write('11 12068.66  \n')
        f.write('12 12025.11  \n')
        f.write('13 11977.98  \n')
        f.write('14 11927.28  \n')
        f.write('15 11873.01  \n')
        f.write('16 11815.20  \n')
        f.write('17 11753.86  \n')
        f.write('18 11689.00  \n')
        f.write('19 11620.63  \n')
        f.write('20 11548.78  \n')
        f.write('21 11473.46  \n')
        f.write('22 11394.68  \n')
        f.write('23 11312.48  \n')
        f.write('24 11226.86  \n')
        f.write('25 11137.85  \n')
        f.write('26 11045.48  \n')
        f.write('27 10949.76  \n')
        f.write('28 10850.71  \n')
        f.write('29 10748.37  \n')
        f.write('30 10642.76  \n')
        f.write('31 10553.91  \n')
        f.write('32 10421.84  \n')
        f.write('33 10306.58  \n')
        f.write('34 10118.16  \n')
        f.write('35 10066.62  \n')
        f.write('36 9941.99  \n')
        f.write('37 9814.29  \n')
        f.write('38 9683.56  \n')
        f.write('39 9549.85  \n')
        f.write('40 9413.17  \n')
        f.write('41 9273.58  \n')
        f.write('42 9131.11  \n')
        f.write('43 8985.79  \n')
        f.write('44 8837.67  \n')
        f.write('45 8686.79  \n')
        f.write('46 8533.19  \n')
        f.write('47 8376.92  \n')
        f.write('48 8218.01  \n')
        f.write('49 8056.52  \n')
        f.write('50 7892.49  \n')
        f.write('51 7725.96  \n')
        f.write('52 7556.99  \n')
        f.write('53 7385.63  \n')
        f.write('54 7211.92  \n')
        f.write('55 7035.91  \n')
        f.write('56 6857.67  \n')
        f.write('57 6677.23  \n')
        f.write('58 6494.67  \n')
        f.write('59 6310.02  \n')

def make_stub(program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker"):  #创建ver02.stub文件
    with open(program_dir+'/ver02.stub', 'w') as f:
        f.write('C NCLFORTSTART  \n')    
        f.write('    subroutine distri(nx,ny,xlat,xlon,monday,emi)  \n')
        f.write('        integer nx,ny,monday  \n')
        f.write('        real xlat(nx,ny),xlon(nx,ny),emi(nx,ny,31,24,4)  \n')
        f.write('C NCLEND  \n')

def make_f90(year="2017",month="8",program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker"):  #创建ver02.f90文件
    with open(program_dir+'/ver02.f90', 'w') as f:
        f.write("subroutine distri(nx,ny,xlat,xlon,monday,emi)  \n")
        f.write("    integer nx,ny,monday  \n")
        f.write("    real xlat(nx,ny),xlon(nx,ny),emi(nx,ny,31,24,4)  !emi(nx,ny,31var,24h,4level)  \n")
        f.write("    integer,parameter::spe_cb05=25,spe_radm2=31,row=200,col=320,clas=5,level=4  \n")
        f.write("    integer i,j,p,q,ii  \n")
        f.write("    real::dayfac(clas,24),dayfacave(clas),toltcb05(clas,spe_cb05,row,col) &  \n")
        f.write("            ,toltradm2(clas,spe_radm2,row,col)=0., &  \n")
        f.write("    toltradm2assis(24,clas,spe_radm2,row,col)=0.,emiassis(24,spe_radm2,row,col,level),tra_area(60,2)  \n")
        f.write("    character*20 cha01,cha02(clas),cha03,cha04(spe_cb05)  \n")
        f.write("    character*7 ename(spe_radm2)  \n")
        f.write("    open(12,file='"+program_dir+"/emidata/trapezoid_area.dat',status='old')  \n")
        f.write("    read(12,*)((tra_area(i,j),j=1,2),i=1,60)  \n")
        f.write("    emi=0.  \n")
        f.write("    emiassis=0.  \n")                  #使用类似cmaq/smoke的日变化分布。各种排放源时间分布不同。
        f.write("    data (dayfac(1,i),i=1,24)/ &  \n")         #agriculture__',
        f.write("            0.400000000,1.600000000,1.600000000,1.600000000,1.600000000, &  \n")
        f.write("            1.600000000,1.600000000,1.600000000,1.600000000,1.600000000, &  \n")
        f.write("            1.600000000,1.600000000,1.600000000,0.400000000,0.400000000, &  \n")
        f.write("            0.400000000,0.400000000,0.400000000,0.400000000,0.400000000, &  \n")
        f.write("            0.400000000,0.400000000,0.400000000,0.400000000/  \n")
        f.write("    data (dayfac(2,i),i=1,24)/ &  \n")         #'industry__',
        f.write("            0.400000000,1.600000000,1.600000000,1.600000000,1.600000000, &  \n")
        f.write("            1.600000000,1.600000000,1.600000000,1.600000000,1.600000000, &  \n")
        f.write("            1.600000000,1.600000000,1.600000000,0.400000000,0.400000000, &  \n")
        f.write("            0.400000000,0.400000000,0.400000000,0.400000000,0.400000000, &  \n")
        f.write("            0.400000000,0.400000000,0.400000000,0.400000000/  \n")
        f.write("    data (dayfac(3,i),i=1,24)/ &  \n")          #'power__',
        f.write("            1.185185185,1.185185185,1.481481481,1.481481481,1.481481481, &  \n")
        f.write("            1.481481481,1.481481481,1.481481481,1.481481481,1.185185185, &  \n")
        f.write("            1.185185185,0.888888889,0.888888889,0.592592593,0.592592593, &  \n")
        f.write("            0.592592593,0.592592593,0.592592593,0.592592593,0.592592593, &  \n")
        f.write("            0.592592593,0.592592593,0.888888889,0.888888889/  \n")
        f.write("    data (dayfac(4,i),i=1,24)/ &  \n")          #'residential__',
        f.write("            1.454545455,1.212121212,1.212121212,0.969696970,0.969696970,&  \n")
        f.write("            0.969696970,0.969696970,0.969696970,1.212121212,1.696969697, &  \n")
        f.write("            2.181818182,1.939393939,1.696969697,1.454545455,1.212121212, &  \n")
        f.write("            0.727272727,0.484848485,0.242424242,0.242424242,0.242424242, &  \n")
        f.write("            0.242424242,0.242424242,0.484848485,0.96969697/  \n")
        f.write("    data (dayfac(5,i),i=1,24)/ &  \n")           #'transportation__'     
        f.write("            1.656000000,1.488000000,1.488000000,1.488000000,1.224000000,&  \n")
        f.write("            1.056000000,1.560000000,1.560000000,1.560000000,1.632000000, &  \n")
        f.write("            1.608000000,1.080000000,1.032000000,0.984000000,0.840000000, &  \n")
        f.write("            0.576000000,0.456000000,0.336000000,0.240000000,0.192000000, &  \n")
        f.write("            0.144000000,0.216000000,0.360000000,1.224000000/  \n")
        f.write("    cha01='"+year+"_"+int2str_2(month)+"__'     \n")
        f.write("    data cha02 / &  \n")
        f.write("        'agriculture__','industry__','power__','residential__',     &  \n")
        f.write("        'transportation__'/  \n")
        f.write("    cha03='CB05_'  \n")
        f.write("    data cha04 /  &  \n")
        f.write("        'BC  ','ALD2 ','ALDX    ','ETH ','ETHA','ETOH','FORM',&  \n")
        f.write("        'IOLE','ISOP ','MEOH    ','NVOL','OLE ','PAR ','TERP',&  \n")
        f.write("        'TOL ','UNR  ','XYL     ','CO  ','CO2 ','NH3 ','NOx ',&  \n")
        f.write("        'OC  ','PM2.5','PMcoarse','SO2  '/  \n")
        f.write("    data ename /    &  \n")
        f.write("        'e_so2 ','e_no  ','e_ald ','e_hcho','e_ora2',                     &  \n")
        f.write("        'e_nh3 ','e_hc3 ','e_hc5 ','e_hc8 ',                              &  \n")
        f.write("        'e_eth ','e_co  ','e_ol2 ','e_olt ','e_oli ','e_tol ','e_xyl ',    &  \n")
        f.write("        'e_ket ','e_csl ','e_iso ','e_pm25i','e_pm25j',                   &  \n")
        f.write("        'e_so4i','e_so4j','e_no3i','e_no3j','e_orgi','e_orgj','e_eci',    &  \n")
        f.write("        'e_ecj' ,'e_pm10','e_no2' /  \n")
        f.write("  \n")
        f.write("    do i=1,clas    ! 5 kinds of pullute ways  \n")
        f.write("        do j=1,spe_cb05    ! 25 pollutions to read  \n")
        f.write("            if(j==1.or.j==18.or.j==19.or.j==20.or.j==21.or.j==22.or.j==23.or.j==24.or.j==25)then   !pullution without a prefix of cb05  \n")
        f.write("                open(15,file='"+program_dir+"/emidata/"+year+int2str_2(month)+"/'//trim(cha01)//trim(cha02(i)) &     \n")
        f.write("                    //trim(cha04(j))//'.asc',status='old')  \n")
        f.write("            else  \n")
        f.write("                open(15,file='"+program_dir+"/emidata/"+year+int2str_2(month)+"/'//trim(cha01)//trim(cha02(i)) &     \n")
        f.write("                        //trim(cha03)//trim(cha04(j))//'.asc',status='old')  \n")
        f.write("            endif  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)  \n")
        f.write("            read(15,*)((toltcb05(i,j,p,q),q=1,col),p=1,row)  \n")
        f.write("            do p=1,row  \n")
        f.write("                do q=1,col  \n")
        f.write("                    if((toltcb05(i,j,p,q)+9999.0)<=1.e-2)  toltcb05(i,j,p,q)=0.    !toltcb05(5,25,200,320)  \n")
        f.write("                enddo  \n")
        f.write("            enddo  \n")
        f.write("            close(15)  \n")
        f.write("        end do  \n")
        f.write("    end do  \n")
        f.write("    !!************************************************************************************************  \n")
        f.write("    toltradm2(:,1,:,:)=toltcb05(:,25,:,:)                                !so2  \n")
        f.write("    toltradm2(:,2,:,:)=toltcb05(:,21,:,:)*0.9                            !no  \n")
        f.write("    toltradm2(:,3,:,:)=toltcb05(:,2,:,:)+toltcb05(:,3,:,:)                !ald  \n")
        f.write("    toltradm2(:,4,:,:)=toltcb05(:,7,:,:)                                !hcho  \n")
        f.write("    toltradm2(:,5,:,:)=toltcb05(:,11,:,:)                                !ora2 !!not sure  \n")
        f.write("    toltradm2(:,6,:,:)=toltcb05(:,20,:,:)                                !nh3  \n")
        f.write("    toltradm2(:,7,:,:)=toltcb05(:,13,:,:)*0.2                            !hc3  \n")
        f.write("    toltradm2(:,8,:,:)=toltcb05(:,13,:,:)*0.4                            !hc5  \n")
        f.write("    toltradm2(:,9,:,:)=toltcb05(:,13,:,:)*0.6                            !hc8  \n")
        f.write("    toltradm2(:,10,:,:)=toltcb05(:,5,:,:)                                !eth  \n")
        f.write("    toltradm2(:,11,:,:)=toltcb05(:,18,:,:)                                !co  \n")
        f.write("    toltradm2(:,12,:,:)=toltcb05(:,4,:,:)                                !ol2  \n")
        f.write("    toltradm2(:,13,:,:)=toltcb05(:,12,:,:)                                !olt  \n")
        f.write("    toltradm2(:,14,:,:)=toltcb05(:,8,:,:)                                !oli  \n")
        f.write("    toltradm2(:,15,:,:)=toltcb05(:,15,:,:)                                !tol  \n")
        f.write("    toltradm2(:,16,:,:)=toltcb05(:,17,:,:)                                !xyl  \n")
        f.write("    toltradm2(:,17,:,:)=toltcb05(:,9,:,:)*1.11                                    !ket  \n")
        f.write("    toltradm2(:,18,:,:)=toltcb05(:,9,:,:)*0.4+toltcb05(:,12,:,:)*0.3                        !csl  \n")
        f.write("    toltradm2(:,19,:,:)=toltcb05(:,9,:,:)                                !iso  \n")
        f.write("    toltradm2(:,20,:,:)=toltcb05(:,23,:,:)*0.2                            !pm2.5i  \n")
        f.write("    toltradm2(:,21,:,:)=toltcb05(:,23,:,:)*0.8                            !pm2.5j  \n")
        f.write("    toltradm2(:,22,:,:)=0                                                !so4i  \n")
        f.write("    toltradm2(:,23,:,:)=0                                                !so4j  \n")
        f.write("    toltradm2(:,24,:,:)=0                                                !no3i  \n")
        f.write("    toltradm2(:,25,:,:)=0                                                !no3j  \n")
        f.write("    toltradm2(:,26,:,:)=toltcb05(:,22,:,:)*0.2                            !orgi  \n")
        f.write("    toltradm2(:,27,:,:)=toltcb05(:,22,:,:)*0.8                            !orgj  \n")
        f.write("    toltradm2(:,28,:,:)=toltcb05(:,1,:,:)*0.2                            !eci  \n")
        f.write("    toltradm2(:,29,:,:)=toltcb05(:,1,:,:)*0.8                            !ecj  \n")
        f.write("    toltradm2(:,30,:,:)=toltcb05(:,24,:,:)+toltcb05(:,23,:,:)                !pm10   ! toltradm2(5,31,200,320)  \n")
        f.write("    toltradm2(:,31,:,:)=toltcb05(:,21,:,:)*0.1                            !no2  \n")
        f.write("    !!************************************************************************************************  \n")
        f.write("    !!*************************************** convert units ******************************************  \n")
        f.write("    do i=1,row  \n")
        f.write("        p=anint(10.+(i-1)*0.25)+1  \n")
        f.write("        do j=1,30  \n")
        f.write("            if(j>=20)then  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e12/(monday*24*60*60*(tra_area(p,2)/16.)*1000*1000)   !aerosols  \n")
        f.write("            elseif(j==1)then  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.)*64)  !so2  \n")
        f.write("            elseif(j==2)then  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.)*30)  !no  \n")
        f.write("            elseif(j==6)then  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.)*17)  !nh3  \n")
        f.write("            elseif(j==11)then  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.)*28)  !co  \n")
        f.write("            else  \n")
        f.write("                toltradm2(:,j,i,:)=toltradm2(:,j,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.))     !cb05  \n")
        f.write("            endif  \n")
        f.write("        enddo  \n")
        f.write("        toltradm2(:,31,i,:)=toltradm2(:,31,i,:)*1.e6/(monday*24*(tra_area(p,2)/16.)*46)         !no2  \n")
        f.write("    enddo  \n")
        f.write("    !!*************************************** end convert units***************************************  \n")
        f.write("    !!*************************************** day factor**********************************************  \n")
        f.write("    do i=1,clas  \n")
        f.write("        dayfacave(i)=sum(dayfac(i,:))/24  \n")
        f.write("        do j=1,24  \n")
        f.write("            toltradm2assis(j,i,:,:,:)=toltradm2(i,:,:,:)*dayfac(i,j)/dayfacave(i)  !toltradm2assis(24h,5kind,31var,200,320)  \n")
        f.write("        enddo  \n")
        f.write("    enddo  \n")
        f.write("    !!*************************************** end day factor *****************************************  \n")
        f.write("    !do i=1,5     !5 kinds of pullute ways  \n")
        f.write("    emiassis(:,:,:,:,1)=emiassis(:,:,:,:,1)+1.0*toltradm2assis(:,1,:,:,:)+0.7*toltradm2assis(:,2,:,:,:)  &  \n")
        f.write("               +0.0*toltradm2assis(:,3,:,:,:)+1.0*toltradm2assis(:,4,:,:,:)+1.0*toltradm2assis(:,5,:,:,:)   \n")
        f.write("    !emiassis(24h,31var,200,320,4level)  \n")
        f.write("    emiassis(:,:,:,:,2)=emiassis(:,:,:,:,2)+0.0*toltradm2assis(:,1,:,:,:)+0.2*toltradm2assis(:,2,:,:,:)  &  \n")
        f.write("               +0.3*toltradm2assis(:,3,:,:,:)+0.0*toltradm2assis(:,4,:,:,:)+0.0*toltradm2assis(:,5,:,:,:)  \n")
        f.write("    emiassis(:,:,:,:,3)=emiassis(:,:,:,:,3)+0.0*toltradm2assis(:,1,:,:,:)+0.1*toltradm2assis(:,2,:,:,:)  &  \n")
        f.write("               +0.6*toltradm2assis(:,3,:,:,:)+0.0*toltradm2assis(:,4,:,:,:)+0.0*toltradm2assis(:,5,:,:,:)  \n")
        f.write("    emiassis(:,:,:,:,4)=emiassis(:,:,:,:,4)+0.0*toltradm2assis(:,1,:,:,:)+0.0*toltradm2assis(:,2,:,:,:)  &  \n")
        f.write("               +0.1*toltradm2assis(:,3,:,:,:)+0.0*toltradm2assis(:,4,:,:,:)+0.0*toltradm2assis(:,5,:,:,:)  \n")
        f.write("    !enddo  \n")
        f.write("    do i=1,ny  \n")
        f.write("        do j=1,nx  \n")
        f.write("            p=int((60.0-xlat(j,i))*100)/25                                          !nearest grid  \n")
        f.write("            q=int((xlon(j,i)-70.0)*100)/25  \n")
        f.write("            if(p<=199.and.q<=319.and.p>=1.and.q>=1)then  \n")
        f.write("                do ii=1,spe_radm2  \n")
        f.write("                    emi(j,i,ii,:,:)        =emiassis(:,ii,p,q,:)  \n")
        f.write("                enddo  \n")
        f.write("            endif  \n")
        f.write("        enddo  \n")
        f.write("    enddo  \n")
        f.write("    return  \n")
        f.write("end subroutine distri \n")

def make_ncl(year="2017",month="8",domain_id="04",program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker",wrfinput_path="/home/IncubatorShokuhou/wrfchem_emission_maker"):
    with open(program_dir+'/ver02.ncl', 'w') as f:
        f.write('	load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl"	  \n')
        f.write('	load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_csm.ncl"	  \n')
        f.write('	load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/contributed.ncl"	  \n')
        f.write('	load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/shea_util.ncl"	  \n')
        f.write('	load "$NCARG_ROOT/lib/ncarg/nclscripts/wrf/WRFUserARW.ncl"	  \n')
        f.write('		  \n')
        f.write('	external COMPUTE "./ver02.so"	  \n')
        f.write('	begin	  \n')
        f.write('	char				= "'+domain_id+'"  \n')
        f.write('	emispecienumber			= 31  \n')
        f.write('	monday				= '+get_month_len(year=int(year),month=int(month))+'  \n')
        f.write('	emidatapath			= "'+program_dir+'/emidata/'+year+int2str_2(month)+'/"  \n')
        f.write('	inputpath			= "'+wrfinput_path+'"  \n')
        f.write('	chem00				= addfile(inputpath+"/wrfchemi_00z_d"+char+".nc","c")  \n')
        f.write('	chem12				= addfile(inputpath+"/wrfchemi_12z_d"+char+".nc","c")  \n')
        f.write('	input				= addfile(inputpath+"/wrfinput_d"+char+".nc","r")  \n')
        f.write('  \n')
        f.write('	xlat				= input->XLAT(0,:,:)  \n')
        f.write('	xlon				= input->XLONG(0,:,:)  \n')
        f.write('	dim				= dimsizes(xlat)  \n')
        f.write('	ny				= dim(0)  \n')
        f.write('	nx				= dim(1)  \n')
        f.write('	emi				= new((/4,24,emispecienumber,ny,nx/),"float")  \n')
        f.write('	 COMPUTE::distri(nx,ny,xlat,xlon,monday,emi)	  \n')
        f.write('		  \n')
        f.write('	fileattdef(chem00,input)	  \n')
        f.write('	fileattdef(chem12,input)	  \n')
        f.write('	dimnames=(/"Time","DateStrLen","west_east","south_north","emissions_zdim"/)	  \n')
        f.write('	dimSizes=(/12,19,nx,ny,4/)	  \n')
        f.write('	dimunlim=(/False,False,False,False,False/)	  \n')
        f.write('	filedimdef(chem00,dimnames,dimSizes,dimunlim)	  \n')
        f.write('	filedimdef(chem12,dimnames,dimSizes,dimunlim)	  \n')
        f.write('		  \n')
        f.write('	f               = chem00	  \n')
        f.write('	do i=1,2,1	  \n')
        f.write('	if(i.eq.2)then	  \n')
        f.write('	 f              = chem12	  \n')
        f.write('	end if	  \n')
        f.write('	filevardef(f,"Times","character",(/"Time","DateStrLen"/))	  \n')
        f.write('	        aa=(/"2010-08-14_12:00:00","2010-08-14_18:00:00","2010-08-15_00:00:00","2010-08-15_06:00:00","2010-08-15_12:00:00",\	  \n')
        f.write('	        "2010-08-15_18:00:00","2010-08-16_00:00:00","2010-08-16_06:00:00","2010-08-16_12:00:00","2010-08-16_18:00:00","2010-08-17_00:00:00",\	  \n')
        f.write('	        "2010-07-17_06:00:00"/)	  \n')
        f.write('	        b=stringtochar(aa)	  \n')
        f.write('	        f->Times = (/b(:,0:18)/)	  \n')
        f.write('		  \n')
        f.write('	filevardef(f,"E_ISO","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ISO@FieldType = 104	  \n')
        f.write('	 f->E_ISO@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ISO@description = "Isoprene EMISSIONS (Anth. for RADM/RACM, Anth+Bio for CBMZ)"	  \n')
        f.write('	 f->E_ISO@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_ISO@stagger=""	  \n')
        f.write('	 f->E_ISO@ISOordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_SO2","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_SO2@FieldType = 104	  \n')
        f.write('	 f->E_SO2@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_SO2@description = "EMISSION"	  \n')
        f.write('	 f->E_SO2@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_SO2@stagger=""	  \n')
        f.write('	 f->E_SO2@SO2ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_NO","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_NO@FieldType = 104	  \n')
        f.write('	 f->E_NO@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_NO@description = "EMISSION"	  \n')
        f.write('	 f->E_NO@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_NO@stagger=""	  \n')
        f.write('	 f->E_NO@NOordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_CO","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_CO@FieldType = 104	  \n')
        f.write('	 f->E_CO@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_CO@description = "EMISSION"	  \n')
        f.write('	 f->E_CO@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_CO@stagger=""	  \n')
        f.write('	 f->E_CO@COordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ETH","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ETH@FieldType = 104	  \n')
        f.write('	 f->E_ETH@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ETH@description = "EMISSION"	  \n')
        f.write('	 f->E_ETH@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_ETH@stagger=""	  \n')
        f.write('	 f->E_ETH@ETHordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_HC3","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_HC3@FieldType = 104	  \n')
        f.write('	 f->E_HC3@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_HC3@description = "EMISSION"	  \n')
        f.write('	 f->E_HC3@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_HC3@stagger=""	  \n')
        f.write('	 f->E_HC3@HC3ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_HC5","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_HC5@FieldType = 104	  \n')
        f.write('	 f->E_HC5@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_HC5@description = "EMISSION"	  \n')
        f.write('	 f->E_HC5@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_HC5@stagger=""	  \n')
        f.write('	 f->E_HC5@HC3ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_HC8","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_HC8@FieldType = 104	  \n')
        f.write('	 f->E_HC8@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_HC8@description = "EMISSION"	  \n')
        f.write('	 f->E_HC8@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_HC8@stagger=""	  \n')
        f.write('	 f->E_HC8@HC3ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_XYL","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_XYL@FieldType = 104	  \n')
        f.write('	 f->E_XYL@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_XYL@description = "EMISSION"	  \n')
        f.write('	 f->E_XYL@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_XYL@stagger=""	  \n')
        f.write('	 f->E_XYL@XYLordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_OL2","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_OL2@FieldType = 104	  \n')
        f.write('	 f->E_OL2@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_OL2@description = "EMISSION"	  \n')
        f.write('	 f->E_OL2@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_OL2@stagger=""	  \n')
        f.write('	 f->E_OL2@OL2ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_OLT","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_OLT@FieldType = 104	  \n')
        f.write('	 f->E_OLT@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_OLT@description = "EMISSION"	  \n')
        f.write('	 f->E_OLT@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_OLT@stagger=""	  \n')
        f.write('	 f->E_OLT@OLTordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_OLI","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_OLI@FieldType = 104	  \n')
        f.write('	 f->E_OLI@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_OLI@description = "EMISSION"	  \n')
        f.write('	 f->E_OLI@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_OLI@stagger=""	  \n')
        f.write('	 f->E_OLI@OLIordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_TOL","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_TOL@FieldType = 104	  \n')
        f.write('	 f->E_TOL@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_TOL@description = "EMISSION"	  \n')
        f.write('	 f->E_TOL@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_TOL@stagger=""	  \n')
        f.write('	 f->E_TOL@TOLordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_CSL","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_CSL@FieldType = 104	  \n')
        f.write('	 f->E_CSL@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_CSL@description = "EMISSION"	  \n')
        f.write('	 f->E_CSL@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_CSL@stagger=""	  \n')
        f.write('	 f->E_CSL@CSLordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_HCHO","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_HCHO@FieldType = 104	  \n')
        f.write('	 f->E_HCHO@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_HCHO@description = "EMISSION"	  \n')
        f.write('	 f->E_HCHO@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_HCHO@stagger=""	  \n')
        f.write('	 f->E_HCHO@HCHOordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ALD","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ALD@FieldType = 104	  \n')
        f.write('	 f->E_ALD@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ALD@description = "EMISSION"	  \n')
        f.write('	 f->E_ALD@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_ALD@stagger=""	  \n')
        f.write('	 f->E_ALD@ALDordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_KET","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_KET@FieldType = 104	  \n')
        f.write('	 f->E_KET@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_KET@description = "EMISSION"	  \n')
        f.write('	 f->E_KET@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_KET@stagger=""	  \n')
        f.write('	 f->E_KET@KETordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ORA2","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ORA2@FieldType = 104	  \n')
        f.write('	 f->E_ORA2@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ORA2@description = "EMISSION"	  \n')
        f.write('	 f->E_ORA2@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_ORA2@stagger=""	  \n')
        f.write('	 f->E_ORA2@ORA2ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_NH3","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_NH3@FieldType = 104	  \n')
        f.write('	 f->E_NH3@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_NH3@description = "EMISSION"	  \n')
        f.write('	 f->E_NH3@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_NH3@stagger=""	  \n')
        f.write('	 f->E_NH3@NH3ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_PM25I","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_PM25I@FieldType = 104	  \n')
        f.write('	 f->E_PM25I@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_PM25I@description = "EMISSION RATE OF UNIDEN. PM2.5 MASS"	  \n')
        f.write('	 f->E_PM25I@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_PM25I@stagger=""	  \n')
        f.write('	 f->E_PM25I@PM25Iordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_PM25J","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_PM25J@FieldType = 104	  \n')
        f.write('	 f->E_PM25J@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_PM25J@description = "EMISSION RATE OF J-MODE UNIDEN. PM2.5 MASS"	  \n')
        f.write('	 f->E_PM25J@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_PM25J@stagger=""	  \n')
        f.write('	 f->E_PM25J@PM25Jordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_PM_10","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_PM_10@FieldType = 104	  \n')
        f.write('	 f->E_PM_10@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_PM_10@description = "EMISSION"	  \n')
        f.write('	 f->E_PM_10@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_PM_10@stagger=""	  \n')
        f.write('	 f->E_PM_10@PM10ordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ECI","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ECI@FieldType = 104	  \n')
        f.write('	 f->E_ECI@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ECI@description = "EMISSION RATE OF I-MODE EC"	  \n')
        f.write('	 f->E_ECI@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_ECI@stagger=""	  \n')
        f.write('	 f->E_ECI@ECIordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ECJ","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ECJ@FieldType = 104	  \n')
        f.write('	 f->E_ECJ@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ECJ@description = "EMISSION RATE OF J-MODE EC"	  \n')
        f.write('	 f->E_ECJ@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_ECJ@stagger=""	  \n')
        f.write('	 f->E_ECJ@ECJordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ORGI","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ORGI@FieldType = 104	  \n')
        f.write('	 f->E_ORGI@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ORGI@description = "EMISSION RATE OF I-MODE ORG. AER."	  \n')
        f.write('	 f->E_ORGI@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_ORGI@stagger=""	  \n')
        f.write('	 f->E_ORGI@ORGIordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_ORGJ","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_ORGJ@FieldType = 104	  \n')
        f.write('	 f->E_ORGJ@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_ORGJ@description = "EMISSION RATE OF J-MODE ORG. AER."	  \n')
        f.write('	 f->E_ORGJ@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_ORGJ@stagger=""	  \n')
        f.write('	 f->E_ORGJ@ORGJordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_SO4I","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_SO4I@FieldType = 104	  \n')
        f.write('	 f->E_SO4I@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_SO4I@description = "EMISSION RATE OF J-MODE ORG. AER."	  \n')
        f.write('	 f->E_SO4I@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_SO4I@stagger=""	  \n')
        f.write('	 f->E_SO4I@SO4Iordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_SO4J","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_SO4J@FieldType = 104	  \n')
        f.write('	 f->E_SO4J@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_SO4J@description = "EMISSION"	  \n')
        f.write('	 f->E_SO4J@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_SO4J@stagger=""	  \n')
        f.write('	 f->E_SO4J@SO4Jordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_NO3I","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_NO3I@FieldType = 104	  \n')
        f.write('	 f->E_NO3I@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_NO3I@description = "EMISSION"	  \n')
        f.write('	 f->E_NO3I@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_NO3I@stagger=""	  \n')
        f.write('	 f->E_NO3I@NO3Iordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_NO3J","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_NO3J@FieldType = 104	  \n')
        f.write('	 f->E_NO3J@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_NO3J@description = "EMISSION"	  \n')
        f.write('	 f->E_NO3J@units ="ug/m3 m/s"	  \n')
        f.write('	 f->E_NO3J@stagger=""	  \n')
        f.write('	 f->E_NO3J@NO3Jordinates = " XLONG XLAT"	  \n')
        f.write('	filevardef(f,"E_NO2","float",(/"Time","emissions_zdim","south_north","west_east"/))	  \n')
        f.write('	 f->E_NO@FieldType = 104	  \n')
        f.write('	 f->E_NO@MemoryOrder = "XYZ"	  \n')
        f.write('	 f->E_NO@description = "EMISSION"	  \n')
        f.write('	 f->E_NO@units ="mol km^-2 hr^-1"	  \n')
        f.write('	 f->E_NO@stagger=""	  \n')
        f.write('	 f->E_NO@NOordinates = " XLONG XLAT"	  \n')
        f.write('		  \n')
        f.write('	end do	  \n')
        f.write('		  \n')
        f.write('	f	= chem00	  \n')
        f.write('	do t	= 0,23,1	  \n')
        f.write('	 tt	= t	  \n')
        f.write('	 print((/t/))	  \n')
        f.write('	 if(t.gt.11)then	  \n')
        f.write('	  f	= chem12	  \n')
        f.write('	  tt	= tt-12	  \n')
        f.write('	 end if	  \n')
        f.write('	 f->E_SO2(tt,:,:,:)		= (/emi(:,t,0,:,:)/)	  \n') #emi= new((/4,24,emispecienumber,ny,nx/),"float")
        f.write('	 f->E_NO(tt,:,:,:)		= (/emi(:,t,1,:,:)/)	  \n')
        f.write('	 f->E_ALD(tt,:,:,:)		= (/emi(:,t,2,:,:)/)	  \n')
        f.write('	 f->E_HCHO(tt,:,:,:)		= (/emi(:,t,3,:,:)/)	  \n')
        f.write('	 f->E_ORA2(tt,:,:,:)		= (/emi(:,t,4,:,:)/)	  \n')
        f.write('	 f->E_NH3(tt,:,:,:)		= (/emi(:,t,5,:,:)/)	  \n')
        f.write('	 f->E_HC3(tt,:,:,:)		= (/emi(:,t,6,:,:)/)	  \n')
        f.write('	 f->E_HC5(tt,:,:,:)		= (/emi(:,t,7,:,:)/)	  \n')
        f.write('	 f->E_HC8(tt,:,:,:)		= (/emi(:,t,8,:,:)/)	  \n')
        f.write('	 f->E_ETH(tt,:,:,:)		= (/emi(:,t,9,:,:)/)	  \n')
        f.write('	 f->E_CO(tt,:,:,:)		= (/emi(:,t,10,:,:)/)	  \n')
        f.write('	 f->E_OL2(tt,:,:,:)		= (/emi(:,t,11,:,:)/)	  \n')
        f.write('	 f->E_OLT(tt,:,:,:)		= (/emi(:,t,12,:,:)/)	  \n')
        f.write('	 f->E_OLI(tt,:,:,:)		= (/emi(:,t,13,:,:)/)	  \n')
        f.write('	 f->E_TOL(tt,:,:,:)		= (/emi(:,t,14,:,:)/)	  \n')
        f.write('	 f->E_XYL(tt,:,:,:)		= (/emi(:,t,15,:,:)/)	  \n')
        f.write('	 f->E_KET(tt,:,:,:)		= (/emi(:,t,16,:,:)/)	  \n')
        f.write('	 f->E_CSL(tt,:,:,:)		= (/emi(:,t,17,:,:)/)	  \n')
        f.write('	 f->E_ISO(tt,:,:,:)		= (/emi(:,t,18,:,:)/)	  \n')
        f.write('	 f->E_PM25I(tt,:,:,:)		= (/emi(:,t,19,:,:)/)	  \n')
        f.write('	 f->E_PM25J(tt,:,:,:)		= (/emi(:,t,20,:,:)/)	  \n')
        f.write('	 f->E_SO4I(tt,:,:,:)		= (/emi(:,t,21,:,:)/)	  \n')
        f.write('	 f->E_SO4J(tt,:,:,:)		= (/emi(:,t,22,:,:)/)	  \n')
        f.write('	 f->E_NO3I(tt,:,:,:)		= (/emi(:,t,23,:,:)/)	  \n')
        f.write('	 f->E_NO3J(tt,:,:,:)		= (/emi(:,t,24,:,:)/)	  \n')
        f.write('	 f->E_ORGI(tt,:,:,:)		= (/emi(:,t,25,:,:)/)	  \n')
        f.write('	 f->E_ORGJ(tt,:,:,:)		= (/emi(:,t,26,:,:)/)	  \n')
        f.write('	 f->E_ECI(tt,:,:,:)		= (/emi(:,t,27,:,:)/)	  \n')
        f.write('	 f->E_ECJ(tt,:,:,:)		= (/emi(:,t,28,:,:)/)	  \n')
        f.write('	 f->E_PM_10(tt,:,:,:) 		= (/emi(:,t,29,:,:)/)	  \n')
        f.write('	 f->E_NO(tt,:,:,:)		= (/emi(:,t,30,:,:)/)	  \n')
        f.write('	end do	  \n')
        #f.write('	system("mv -f " + inputpath+"/wrfchemi_00z_d"+char+".nc "+inputpath+"/wrfchemi_00z_d"+char)	  \n')
        #f.write('	system("mv -f " + inputpath+"/wrfchemi_12z_d"+char+".nc "+inputpath+"/wrfchemi_12z_d"+char)	  \n')
        f.write('	end	  \n')

def make_emissions(base_year="2017",base_month="8",wrf_domain="02",program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker",wrfinput_path="/home/IncubatorShokuhou/wrfchem_emission_maker"):
    make_trapezoid_area(program_dir=program_dir)
    make_stub(program_dir=program_dir)
    make_f90(year=base_year,month=base_month,program_dir=program_dir)
    make_ncl(year=base_year,month=base_month,domain_id=wrf_domain,program_dir=program_dir,wrfinput_path=wrfinput_path)
    os.system("WRAPIT "+program_dir+"/ver02.stub "+program_dir+"/ver02.f90")
    os.system("ncl "+program_dir+"/ver02.ncl")

def main():
    base_year="2016"   #清华源数据年份
    base_month="8"     #清华源数据月份
    program_dir="/home/IncubatorShokuhou/wrfchem_emission_maker" #python程序所在目录
    wrfinput_path="/home/IncubatorShokuhou/wrfchem_emission_maker/wrfinput" #wrfinput所在目录
    wrfchemi_out_path="/home/IncubatorShokuhou/wrfchem_emission_maker/wrfchemi" #排放源文件输出目录

    mkdir(program_dir) #创建目标目录
    mkdir(program_dir+'/emidata') #创建清华源所在目录
    mkdir(wrfinput_path) #创建wrfinput所在目录
    mkdir(wrfchemi_out_path) #创建排放源文件输出目录

    wrfinput_num=os.popen('ls '+wrfinput_path+'/wrfinput_d* | wc -l').read()  #读取wrfinput开头的文件数
    for wrfdomain_id in range(1,int(wrfinput_num)+1,1):
        make_emissions(base_year=base_year,base_month=base_month,wrf_domain=int2str_2(wrfdomain_id),program_dir=program_dir,wrfinput_path=wrfinput_path)
        os.system("mv  "+wrfinput_path+"/wrfchemi_00z_d"+int2str_2(wrfdomain_id)+".nc  "+wrfchemi_out_path+"/wrfchemi_00z_d"+int2str_2(wrfdomain_id)+"")
        os.system("mv  "+wrfinput_path+"/wrfchemi_12z_d"+int2str_2(wrfdomain_id)+".nc  "+wrfchemi_out_path+"/wrfchemi_12z_d"+int2str_2(wrfdomain_id)+"")

if __name__ == "__main__":
    main()
